# Generated by Django 5.1.3 on 2024-12-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_coment_coment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='post',
        ),
        migrations.AddField(
            model_name='coment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
        migrations.AddField(
            model_name='post',
            name='coment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.coment'),
        ),
    ]
