# Generated by Django 5.1.3 on 2024-12-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_coment_post_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coment',
            field=models.ManyToManyField(to='blog.coment'),
        ),
    ]
