# Generated by Django 5.1.3 on 2024-12-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='coment',
            new_name='comment',
        ),
    ]
